import type {
  PlanningSession,
  RoadmapItem,
  PMIntake,
  ProductDesignInputs,
  ContentDesignInputs,
} from '../domain/types'

export const demoSession: PlanningSession = {
  id: 'demo',
  name: 'Payments Q2 2026',
  planning_period: '2026-Q2',
  weeks_per_period: 13,
  sprint_length_weeks: 2,
  ux_designers: 3,
  content_designers: 2,
  created_by: 'demo-user',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
}

export const demoItems: RoadmapItem[] = [
  {
    id: 'item-1',
    planning_session_id: 'demo',
    short_key: 'F1',
    name: 'New Payment Method: Buy Now Pay Later',
    initiative: 'Revenue',
    team_name: 'Payments',
    priority: 1,
    status: 'ready_for_sizing',
    uxSizeBand: 'L',
    uxFocusWeeks: 0,
    uxWorkWeeks: 0,
    contentSizeBand: 'L',
    contentFocusWeeks: 0,
    contentWorkWeeks: 0,
  },
  {
    id: 'item-2',
    planning_session_id: 'demo',
    short_key: 'F2',
    name: 'Enhanced Checkout Flow',
    initiative: 'New Users',
    team_name: 'Payments',
    priority: 2,
    status: 'ready_for_sizing',
    uxSizeBand: 'M',
    uxFocusWeeks: 0,
    uxWorkWeeks: 0,
    contentSizeBand: 'S',
    contentFocusWeeks: 0,
    contentWorkWeeks: 0,
  },
  {
    id: 'item-3',
    planning_session_id: 'demo',
    short_key: 'F3',
    name: 'Payment Security Dashboard Updates',
    initiative: 'Revenue',
    team_name: 'Payments',
    priority: 3,
    status: 'ready_for_sizing',
    uxSizeBand: 'S',
    uxFocusWeeks: 0,
    uxWorkWeeks: 0,
    contentSizeBand: 'S',
    contentFocusWeeks: 0,
    contentWorkWeeks: 0,
  },
]

export const demoIntakes: PMIntake[] = [
  {
    roadmap_item_id: 'item-1',
    objective: 'Launch BNPL payment option to increase average order value',
    kpis: JSON.stringify(['AOV increase', 'Conversion rate', 'Payment completion rate']),
    goals: 'Increase revenue by 15% through BNPL adoption',
    market: 'US, UK, Canada',
    audience: 'Millennials and Gen Z shoppers',
    timeline: 'Q2 2026',
    requirements_business: 'Integrate with third-party BNPL provider',
    requirements_technical: 'API integration, payment gateway updates',
    requirements_design: 'New payment method selection UI, terms and conditions flow',
    surfaces_in_scope: JSON.stringify({
      mobile: ['iOS', 'Android'],
      web: true,
      other: [],
    }),
    new_or_existing: 'new',
  },
  {
    roadmap_item_id: 'item-2',
    objective: 'Reduce checkout abandonment by simplifying payment flow',
    kpis: JSON.stringify(['Checkout completion rate', 'Time to checkout']),
    goals: 'Reduce cart abandonment by 20%',
    market: 'Global',
    audience: 'All users',
    timeline: 'Q2 2026',
    requirements_business: 'Streamline checkout process',
    requirements_technical: 'Frontend optimization, payment validation improvements',
    requirements_design: 'Simplified form design, better error handling',
    surfaces_in_scope: JSON.stringify({
      mobile: ['iOS', 'Android'],
      web: true,
      other: [],
    }),
    new_or_existing: 'existing',
  },
  {
    roadmap_item_id: 'item-3',
    objective: 'Update security dashboard with new fraud detection features',
    kpis: JSON.stringify(['Fraud detection rate', 'User trust scores']),
    goals: 'Improve fraud detection by 25%',
    market: 'Global',
    audience: 'Security team and power users',
    timeline: 'Q2 2026',
    requirements_business: 'Display new fraud detection metrics',
    requirements_technical: 'Backend API for fraud data',
    requirements_design: 'Dashboard updates, new data visualizations',
    surfaces_in_scope: JSON.stringify({
      mobile: [],
      web: true,
      other: [],
    }),
    new_or_existing: 'existing',
  },
]

export const demoProductDesignInputs: ProductDesignInputs[] = [
  {
    roadmap_item_id: 'item-1',
    net_new_patterns: true,
    changes_to_information_architecture: true,
    multiple_user_states_or_paths: true,
    significant_edge_cases_or_error_handling: true,
    responsive_or_adaptive_layouts: true,
    other: 'New payment method selection, terms acceptance flow',
  },
  {
    roadmap_item_id: 'item-2',
    net_new_patterns: false,
    changes_to_information_architecture: false,
    multiple_user_states_or_paths: false,
    significant_edge_cases_or_error_handling: true,
    responsive_or_adaptive_layouts: true,
    other: 'Improvements to existing checkout flow',
  },
  {
    roadmap_item_id: 'item-3',
    net_new_patterns: false,
    changes_to_information_architecture: false,
    multiple_user_states_or_paths: false,
    significant_edge_cases_or_error_handling: false,
    responsive_or_adaptive_layouts: false,
    other: 'Dashboard updates only',
  },
]

export const demoContentDesignInputs: ContentDesignInputs[] = [
  {
    roadmap_item_id: 'item-1',
    is_content_required: 'yes',
    financial_or_regulated_language: true,
    user_commitments_or_confirmations: true,
    claims_guarantees_or_promises: true,
    trust_sensitive_moments: true,
    ai_driven_or_personalized_decisions: false,
    ranking_recommendations_or_explanations: false,
    legal_policy_or_compliance_review: 'yes',
    introducing_new_terminology: true,
    guidance_needed: 'high',
  },
  {
    roadmap_item_id: 'item-2',
    is_content_required: 'yes',
    financial_or_regulated_language: false,
    user_commitments_or_confirmations: false,
    claims_guarantees_or_promises: false,
    trust_sensitive_moments: false,
    ai_driven_or_personalized_decisions: false,
    ranking_recommendations_or_explanations: false,
    legal_policy_or_compliance_review: 'no',
    introducing_new_terminology: false,
    guidance_needed: 'minimal',
  },
  {
    roadmap_item_id: 'item-3',
    is_content_required: 'yes',
    financial_or_regulated_language: false,
    user_commitments_or_confirmations: false,
    claims_guarantees_or_promises: false,
    trust_sensitive_moments: false,
    ai_driven_or_personalized_decisions: false,
    ranking_recommendations_or_explanations: false,
    legal_policy_or_compliance_review: 'no',
    introducing_new_terminology: false,
    guidance_needed: 'some',
  },
]
